# Generated by Django 3.1.2 on 2020-10-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=5000)),
                ('video', models.URLField()),
                ('pdf', models.FileField(upload_to=None)),
                ('comentario', models.CharField(max_length=5000)),
                ('fechaEntrega', models.DateField()),
                ('fechaCreacion', models.DateField()),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('No entregado', 'No entregado'), ('Revisado', 'Revisado')], default='No entregado', max_length=200)),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='gestionUsuario.usuario')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuario.usuario')),
            ],
        ),
    ]
