# Generated by Django 3.1.2 on 2020-11-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=5000)),
                ('video', models.URLField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to=None)),
                ('comentario', models.CharField(blank=True, max_length=5000)),
                ('fechaEntrega', models.DateField(blank=True, default=None, null=True)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('No entregado', 'No entregado'), ('Revisado', 'Revisado')], default='No entregado', max_length=200)),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='actividades.categoria')),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuario.profesional')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuario.usuario')),
            ],
        ),
    ]
