# Generated by Django 3.1.2 on 2020-10-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuario', '0001_initial'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='comentario',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fechaEntrega',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='idProfesional',
            field=models.ForeignKey(limit_choices_to={'categoria': 'Profesional'}, on_delete=django.db.models.deletion.CASCADE, related_name='idProfesional', to='gestionUsuario.usuario'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='pdf',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
