# Generated by Django 3.1.2 on 2020-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20201026_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaEntrega',
            field=models.DateField(blank=True, default=None),
        ),
    ]
