# Generated by Django 3.1.2 on 2020-10-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuario', '0001_initial'),
        ('actividades', '0004_auto_20201026_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='idUsuario',
            field=models.ForeignKey(limit_choices_to={'categoria': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuario.usuario'),
        ),
    ]
